import { Link } from '@tanstack/react-router'
import { CatalogLink, useCatalogDestination } from './CatalogLink'
import { useUnavailable } from './MarketShell'
export function Hero() {
  const search = useCatalogDestination()
  return <section className="home-hero"><div className="hero-copy"><p>Bem-vindo à Kurio</p><h1><span className="desktop-title">SEJA DONO DO FUTURO<br />DA ARTE DIGITAL</span><span className="mobile-title">SEJA DONO DA<br />CULTURA DIGITAL</span></h1><p className="hero-description"><span className="desktop-title">Descubra NFTs de criadores emergentes e consagrados. Colecione arte digital rara, apoie artistas e tenha uma parte da cultura da internet.</span><span className="mobile-title">Descubra NFTs selecionados de criadores do mundo todo.</span></p><CatalogLink className="hero-cta">EXPLORAR <span className="mobile-title">→</span></CatalogLink></div><div className="hero-art"><Link to="/nfts/$nftId" state={{ catalogSearch: search }} search={{ edition: 'fifty', quantity: 1 }} params={{ nftId: 'emerald-042' }}><img src="/assets/figma/8f387.png" alt="Emerald Ape com óculos e jaqueta verde" width="450" height="450" fetchPriority="high" /></Link><img className="hero-mini" src="/assets/figma/83794.png" alt="Sage Nomad" width="58" height="58" /></div><picture className="hero-dots"><source media="(max-width:639px)" srcSet="/assets/figma/c6c5e.svg" /><img src="/assets/figma/a11b7.svg" width="40" height="8" alt="" /></picture></section>
}
export function HomeSections() {
  const unavailable = useUnavailable()
  const posts = [['9add2.png', 'Como funciona a propriedade de NFTs', 'Aprenda a colecionar, negociar e verificar ativos digitais.'], ['8f387.png', '10 artistas digitais para acompanhar', 'Conheça criadores que moldam a cultura digital.'], ['83794.png', 'Raridade, atributos e procedência', 'Entenda raridade, procedência, direitos autorais e utilidade.'], ['b7cfc.png', 'Como proteger sua carteira', 'Proteja sua carteira, seus NFTs e sua identidade.']]
  return <><section className="promos">{[['8f387.png', 'Lançamentos gênesis de edição limitada', 'Colecione edições escassas diretamente dos criadores antes da revelação pública.'], ['9add2.png', 'Arte digital selecionada e muito mais', 'Explore novos artistas, coleções verificadas e obras digitais que definem a cultura.']].map(([image, title, text]) => <article key={image}><img src={`/assets/figma/${image}`} alt="" width="292" height="250" loading="lazy" /><div><h2>{title}</h2><p>{text}</p><CatalogLink>Explorar →</CatalogLink></div></article>)}</section><section className="blog"><h2>Diário da Cunhagem</h2><p>Histórias, guias e insights para colecionadores sobre o universo da propriedade digital.</p><div className="blog-cards">{posts.map(([image, title, text], i) => <article key={image}><img src={`/assets/figma/${image}`} alt="" width="268" height="195" loading="lazy" /><div><p>{12 + i} de setembro | Leitura de {i === 0 ? 6 : 2} min</p><h3>{title}</h3><p>{text}</p><button onClick={() => unavailable('Conteúdo editorial')}>Ler mais →</button></div></article>)}</div></section></>
}
