import { expect, test, type Page } from '@playwright/test'
async function login(page: Page, name = 'ana', password = 'Kurio123!') { await page.getByLabel('E-mail', { exact: true }).fill(`${name}@kurio.test`); await page.getByLabel('Senha', { exact: true }).fill(password); await page.locator('.auth-form').getByRole('button', { name: 'Entrar', exact: true }).click(); await expect(page.getByText(`Sessão: ${name}`, { exact: true })).toBeAttached() }
test.beforeEach(async ({ page }) => { await page.goto('/preparation'); await expect(page.getByRole('link', { name: 'Abrir prova de integração' })).toBeVisible(); await page.evaluate(() => fetch('/api/__commerce/scenario', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reset' }) })); await page.goto('/account/profile'); await expect(page).toHaveURL(/\/login/); await login(page) })
test('profile validates, keeps failed draft, persists, and isolates accounts', async ({ page }) => {
  const form = page.getByRole('form', { name: 'Dados do perfil' })
  await form.getByLabel('Nome de exibição').fill('Ana Colecionadora')
  await form.getByLabel('Nome de usuário').fill('invalid.name'); await form.getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(form.getByText('Use de 3 a 32 letras, números, _ ou -.')).toBeVisible()
  await expect(form.getByLabel('Nome de usuário')).toHaveAttribute('aria-invalid', 'true')
  await form.getByLabel('Nome de usuário').fill('ana'); await form.getByLabel('E-mail').fill('bruno@kurio.test'); await form.getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(form.getByRole('alert')).toContainText('já utilizado')
  await form.getByLabel('E-mail').fill('ana@kurio.test'); await form.getByLabel('Nome ENS (opcional)').fill('ana.kurio.eth'); await form.getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(form.getByRole('status')).toHaveText('Perfil salvo.')
  await page.reload(); await expect(form.getByLabel('Nome de exibição')).toHaveValue('Ana Colecionadora'); await expect(form.getByLabel('Nome ENS (opcional)')).toHaveValue('ana.kurio.eth')
  await page.getByRole('button', { name: 'Trocar usuário' }).click(); await login(page, 'bruno')
  await expect(form.getByLabel('Nome de exibição')).toHaveValue('bruno')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('avatar rejects invalid bytes, uploads local PNG, persists and removes', async ({ page }) => {
  await page.getByLabel('Avatar', { exact: true }).setInputFiles({ name: 'bad.png', mimeType: 'image/png', buffer: Buffer.from('invalid') })
  await expect(page.getByRole('alert')).toContainText('decodificar')
  await page.getByLabel('Avatar', { exact: true }).setInputFiles('public/assets/figma/8f387.png')
  await expect(page.getByTestId('avatar')).toBeVisible()
  await page.reload(); await expect(page.getByTestId('avatar')).toBeVisible()
  await page.getByRole('button', { name: 'Remover avatar' }).click(); await expect(page.getByTestId('avatar')).toHaveCount(0)
  await page.reload(); await expect(page.getByRole('button', { name: 'Remover avatar' })).toBeDisabled()
})
test('password API errors, confirmation, old credentials rejected and new password works', async ({ page }) => {
  const form = page.getByRole('form', { name: 'Alterar senha' })
  await form.getByLabel('Senha atual').fill('Incorreta123!'); await form.getByLabel(/^Nova senha/).fill('Alterada123!'); await form.getByLabel('Confirmar nova senha').fill('Alterada123!'); await form.getByRole('button', { name: 'Salvar senha' }).click()
  await expect(form.getByRole('alert')).toHaveText('Senha atual incorreta.')
  await form.getByLabel('Senha atual').fill('Kurio123!'); await form.getByLabel('Confirmar nova senha').fill('Diferente123!'); await form.getByRole('button', { name: 'Salvar senha' }).click(); await expect(form.getByText('As senhas não coincidem.')).toBeVisible()
  await form.getByLabel('Confirmar nova senha').fill('Alterada123!'); await form.getByRole('button', { name: 'Salvar senha' }).click(); await expect(form.getByRole('status')).toHaveText('Senha alterada.')
  const state = await page.evaluate(() => localStorage.getItem('kurio-commerce-v1')!)
  expect(state).not.toContain('Alterada123!'); expect(state).not.toContain('Kurio123!')
  await page.getByRole('button', { name: 'Encerrar sessão' }).click(); await expect(page.getByText(/^Sessão:/)).toHaveCount(0)
  await page.goto('/login?returnTo=/account/profile'); await page.getByLabel('E-mail', { exact: true }).fill('ana@kurio.test'); await page.getByLabel('Senha', { exact: true }).fill('Kurio123!'); await page.locator('.auth-form').getByRole('button', { name: 'Entrar', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('E-mail ou senha inválidos')
  await login(page, 'ana', 'Alterada123!'); await expect(page).toHaveURL(/\/account\/profile/)
})
test('wallets validate address, persist primary/secondary, reject duplicates and reuse without another record', async ({ page }) => {
  await page.getByRole('navigation', { name: 'Minha conta' }).getByRole('link', { name: 'Carteiras', exact: true }).click()
  const primary = page.getByRole('form', { name: 'Carteira principal' })
  await primary.getByLabel('Endereço da carteira').fill('0x123'); await primary.getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(primary.getByLabel('Endereço da carteira')).toHaveAttribute('aria-invalid', 'true')
  const address = '0x' + '1'.repeat(40)
  await primary.getByLabel('Endereço da carteira').fill(address); await primary.getByRole('button', { name: 'Salvar carteira' }).click(); await expect(primary.getByRole('status')).toHaveText('Carteira salva.')
  await page.reload(); await expect(primary.getByLabel('Endereço da carteira')).toHaveValue(address)
  await primary.getByLabel('Tipo de carteira').selectOption('WalletConnect'); await primary.getByRole('button', { name: 'Salvar carteira' }).click(); await expect(primary.getByRole('status')).toHaveText('Carteira salva.')
  await page.getByLabel('Igual à carteira principal').click(); await expect(page.getByText('A seleção secundária reutiliza a principal. Nenhum registro duplicado é criado.')).toBeVisible(); await page.reload(); await expect(page.getByLabel('Igual à carteira principal')).toBeChecked()
  await page.getByLabel('Igual à carteira principal').click(); await expect(page.getByLabel('Igual à carteira principal')).not.toBeChecked(); await page.getByRole('button', { name: 'Adicionar carteira secundária' }).click()
  const secondary = page.getByRole('form', { name: 'Carteira secundária' })
  await secondary.getByLabel('Endereço da carteira').fill(address); await secondary.getByRole('button', { name: 'Salvar carteira' }).click(); await expect(secondary.getByRole('alert')).toContainText('já cadastrado')
  await secondary.getByLabel('Rede').selectOption('Solana'); await secondary.getByLabel('Endereço da carteira').fill('1'.repeat(32)); await secondary.getByRole('button', { name: 'Salvar carteira' }).click(); await expect(secondary.getByRole('status')).toHaveText('Carteira salva.')
  await page.reload(); await expect(secondary.getByLabel('Rede')).toHaveValue('Solana')
  await page.getByRole('button', { name: 'Trocar usuário' }).click(); await login(page, 'bruno'); await expect(primary.getByLabel('Endereço da carteira')).toHaveValue(''); await expect(page.getByRole('button', { name: 'Adicionar carteira secundária' })).toBeVisible()
  await primary.getByLabel('Endereço da carteira').focus(); await expect(primary.getByLabel('Endereço da carteira')).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
