import { expect, test, type Page } from '@playwright/test'

async function scenario(page: Page, action: string, extra: Record<string, unknown> = {}) {
  const status = await page.evaluate(async ({ action, extra }) => (await fetch('/api/__catalog/scenario', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...extra }) })).status, { action, extra })
  expect(status).toBe(200)
}
async function openFilters(page: Page) {
  const button = page.getByRole('button', { name: 'Abrir filtros' })
  if (await button.isVisible()) { await button.click(); return page.getByRole('dialog', { name: 'Filtros de NFTs' }) }
  return page.locator('.catalog-sidebar')
}
async function closeFilters(page: Page) { const dialog = page.getByRole('dialog', { name: 'Filtros de NFTs' }); if (await dialog.isVisible()) await dialog.getByRole('button', { name: 'Ver resultados' }).click() }
test.beforeEach(async ({ page }) => { await page.goto('/preparation'); await expect(page.getByRole('link', { name: 'Abrir prova de integração' })).toBeVisible(); await scenario(page, 'reset') })

test('malformed URL parameters are validated before reaching the API', async ({ page }) => {
  const rest = page.waitForResponse((response) => response.url().includes('/api/nfts?') && response.status() === 200)
  await page.goto('/?page=-5&sort=bad&collections=unknown&networks=unknown&minPrice=12&maxPrice=1')
  const response = await rest, params = new URL(response.url()).searchParams
  expect(params.get('page')).toBe('1'); expect(params.get('sort')).toBe('recent')
  expect(params.get('collections')).toBe(''); expect(params.get('networks')).toBe('')
  expect(params.get('minPrice')).toBe('1'); expect(params.get('maxPrice')).toBe('12')
  await expect(page.getByLabel('Ordenar NFTs')).toHaveValue('recent')
  await expect(page.getByRole('button', { name: 'Página 1', exact: true })).toHaveAttribute('aria-current', 'page')
})

test('reconnect cancels a slow pre-outage detail snapshot before reconciling', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('nft-emerald-042')).toBeVisible()
  await scenario(page, 'slow', { delay: 3000 })
  await scenario(page, 'disconnect')
  const requested = page.waitForRequest((request) => request.url().endsWith('/api/nfts/emerald-042'))
  await page.getByTestId('nft-emerald-042').getByRole('link', { name: 'Ver Emerald Ape #042' }).click()
  await requested
  await scenario(page, 'change')
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.29 ETH', { timeout: 10000 })
  expect(await page.evaluate(async () => (await (await fetch('/api/nfts/emerald-042')).json()).nft.version)).toBe(2)
})

test('combined URL filters, sorting, pagination, refresh and history', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  await page.getByRole('button', { name: 'Página 2', exact: true }).click()
  await expect(page).toHaveURL(/page=2/)
  const filter = await openFilters(page)
  await filter.getByLabel('Arte digital', { exact: false }).check()
  await filter.getByLabel('Ethereum', { exact: false }).check()
  await closeFilters(page)
  await expect(page).toHaveURL(/page=1/)
  await expect(page).toHaveURL(/digital/)
  await expect(page).toHaveURL(/Ethereum/)
  const descending = page.waitForResponse((response) => response.url().includes('/api/nfts?') && new URL(response.url()).searchParams.get('sort') === 'price-desc' && response.status() === 200)
  await page.getByLabel('Ordenar NFTs').selectOption('price-desc')
  await expect(page).toHaveURL(/price-desc/)
  const names = ((await (await descending).json()) as { items: { name: string }[] }).items.map((item) => item.name)
  await expect(page.locator('.catalog-results .card-name')).toHaveText(names)
  await page.reload()
  await expect(page.locator('.catalog-results .card-name')).toHaveText(names)
  const ascending = page.waitForResponse((response) => response.url().includes('/api/nfts?') && new URL(response.url()).searchParams.get('sort') === 'price-asc' && response.status() === 200)
  await page.getByLabel('Ordenar NFTs').selectOption('price-asc')
  await expect(page).toHaveURL(/price-asc/)
  const ascendingNames = ((await (await ascending).json()) as { items: { name: string }[] }).items.map((item) => item.name)
  await expect(page.locator('.catalog-results .card-name')).toHaveText(ascendingNames)
  await page.goBack()
  await expect(page).toHaveURL(/price-desc/)
  await expect(page.locator('.catalog-results .card-name')).toHaveText(names)
  await page.goForward()
  await expect(page).toHaveURL(/price-asc/)
  await expect(page.locator('.catalog-results .card-name')).toHaveText(ascendingNames)
  const prices = await page.locator('.catalog-results .card-price').allTextContents()
  expect(prices.map((p) => Number.parseFloat(p))).toEqual(prices.map((p) => Number.parseFloat(p)).sort((a, b) => a - b))
})

test('search, empty state, price limits and obsolete response cancellation', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  const search = page.getByLabel('Buscar NFTs', { exact: true })
  await search.fill('Kurio'); await search.press('Enter')
  await expect(page).toHaveURL(/q=Kurio/)
  await page.getByLabel('Buscar NFTs', { exact: true }).fill('Emerald')
  await page.getByLabel('Buscar NFTs', { exact: true }).press('Enter')
  await expect(page.locator('.catalog-results .card-name')).toHaveText(['Emerald Ape #042'])
  await page.waitForTimeout(1000) // allow the deliberately obsolete mock response to finish
  await expect(page.locator('.catalog-results .card-name')).toHaveText(['Emerald Ape #042'])
  await page.getByLabel('Buscar NFTs', { exact: true }).fill('not-an-nft')
  await page.getByLabel('Buscar NFTs', { exact: true }).press('Enter')
  await expect(page.getByRole('heading', { name: 'Nenhum NFT encontrado' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpar busca e filtros' }).click()
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  const filters = await openFilters(page)
  await filters.getByLabel('Preço máximo').focus()
  await page.keyboard.press('Home')
  for (let i = 0; i < 98; i++) await page.keyboard.press('ArrowRight')
  await filters.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await closeFilters(page)
  await expect.poll(() => JSON.parse(new URL(page.url()).searchParams.get('maxPrice') ?? 'null')).toBe('1')
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(3)
})

test('direct detail, gallery, edition/quantity validation, full mobile information and 404', async ({ page }) => {
  await page.goto('/nfts/emerald-042')
  await expect(page.getByRole('heading', { name: 'Emerald Ape #042', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edição 1/1, indisponível' })).toBeDisabled()
  await page.getByRole('button', { name: 'Edição 1/10', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edição 1/10', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const qty = page.getByLabel('Qtd.', { exact: true })
  await qty.fill('4')
  await expect(page.getByRole('button', { name: 'Aumentar quantidade' })).toBeDisabled()
  await qty.fill('5')
  await expect(page.getByRole('alert')).toContainText('quantidade inteira de 1 a 4')
  await qty.fill('1.5')
  await expect(page.getByRole('alert')).toContainText('quantidade inteira')
  await qty.fill('2')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: 'Imagem 2', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Imagem 2', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Ampliar imagem' }).click()
  await expect(page.getByRole('dialog', { name: 'Imagem do NFT' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0) // native closed dialogs are hidden to role queries
  await expect(page.getByText('Contrato:', { exact: true })).toBeVisible()
  await expect(page.getByText('Direitos autorais:', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.19 ETH')
  await page.goto('/nfts/does-not-exist')
  await expect(page.getByRole('heading', { name: 'NFT não encontrado' })).toBeVisible()
})

test('slow loading, reduced motion, REST error and recovery on both screens', async ({ page }) => {
  await scenario(page, 'slow', { delay: 1500 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByText('Carregando catálogo', { exact: true })).toBeVisible()
  await expect(page.locator('.nft-grid .proof-skeleton').first()).toHaveCSS('animation-name', 'none')
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  await scenario(page, 'fail')
  await page.getByLabel('Ordenar NFTs').selectOption('price-asc')
  await expect(page.getByRole('alert')).toContainText('Não foi possível carregar o catálogo')
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  await scenario(page, 'fail')
  await page.goto('/nfts/emerald-042')
  await expect(page.getByRole('heading', { name: 'Não foi possível carregar o NFT' })).toBeVisible()
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.19 ETH')
})

test('Socket.IO updates catalogue/detail, ignores old events, reconciles outage and respects sold-out edition', async ({ page }) => {
  await page.goto('/')
  const card = page.getByTestId('nft-emerald-042')
  await expect(card).toBeVisible()
  await scenario(page, 'change')
  await expect(card.locator('.card-price')).toContainText('1.29 ETH')
  await scenario(page, 'duplicate'); await scenario(page, 'old')
  await expect(card).toHaveAttribute('data-version', '2')
  await card.getByRole('link', { name: 'Ver Emerald Ape #042' }).click()
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.29 ETH')
  await scenario(page, 'change')
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.39 ETH')
  await scenario(page, 'disconnect')
  await expect(page.getByText('Conexão interrompida. A reconexão será automática.', { exact: true }).last()).toBeVisible()
  await scenario(page, 'change')
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toHaveText('1.49 ETH')
  await scenario(page, 'sold-out')
  await expect(page.getByText('Edição esgotada.', { exact: true })).toBeVisible()
  expect(await page.evaluate(async () => (await (await fetch('/api/nfts/emerald-042')).json()).nft.version)).toBe(5)
})

test('keyboard focus, drawer/modal, pending actions and responsive overflow', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
  await page.getByLabel('Buscar NFTs', { exact: true }).focus()
  await expect(page.getByLabel('Buscar NFTs', { exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  const filters = await openFilters(page)
  if (await filters.getAttribute('role') === 'dialog' || await page.getByRole('dialog').isVisible()) {
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Abrir filtros' })).toBeFocused()
  }
  const favorites = page.getByRole('button', { name: 'Favoritos', exact: true })
  if (await favorites.isVisible()) { await favorites.click(); await expect(page.getByRole('dialog', { name: 'Funcionalidade indisponível' })).toContainText('Nenhuma operação'); await page.keyboard.press('Escape') }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/nfts/emerald-042')
  await expect(page.getByTestId('detail-price').filter({ visible: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
