import { expect, test } from '@playwright/test'
import { connect, resetCheckout, setup } from './checkout-support'

for (const [width, height] of [[390,844],[414,896],[440,956]]) {
  test(`mobile reference controls, independent passwords and scroll at ${width}px`, async ({ page }) => {
    await page.setViewportSize({width,height})
    await page.emulateMedia({reducedMotion:'reduce'})
    await resetCheckout(page)
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.goto('/signup')
    const password = page.getByLabel('Senha', {exact:true}), confirmation = page.getByLabel('Confirmar senha', {exact:true})
    await password.fill('Kurio123!'); await confirmation.fill('Kurio123!')
    await page.getByRole('button', {name:'Mostrar confirmação de senha'}).focus()
    await page.keyboard.press('Enter')
    await expect(confirmation).toHaveAttribute('type','text'); await expect(password).toHaveAttribute('type','password')
    await page.getByRole('button', {name:'Mostrar senha',exact:true}).click()
    await page.getByRole('button', {name:'Ocultar confirmação de senha'}).click()
    await expect(password).toHaveAttribute('type','text'); await expect(confirmation).toHaveAttribute('type','password')
    await page.getByLabel('Nome de usuário', {exact:true}).fill('colecionador-com-nome-longo')
    await page.setViewportSize({width,height:Math.floor(height/2)})
    await page.getByRole('button', {name:'Criar perfil',exact:true}).focus(); await page.keyboard.press('Enter')
    await expect(page.getByLabel('E-mail', {exact:true})).toBeFocused()
    await noOverflow(); await page.setViewportSize({width,height})
    await page.goto('/')
    await expect(page.locator('.catalog-results .card-name')).toHaveCount(9)
    await expect(page.locator('.sort-control')).toBeHidden()
    await expect(page.getByRole('navigation',{name:'Navegação mobile'})).toBeVisible()
    const grid = await page.locator('.catalog-results .card-art').evaluateAll(nodes => nodes.slice(0,2).map(node => node.getBoundingClientRect().y))
    expect(grid[1]-grid[0]).toBe(32)
    await page.getByRole('button',{name:'Abrir filtros'}).click()
    const filters = page.getByRole('dialog',{name:'Filtros de NFTs'})
    await filters.getByLabel('Ordenar NFTs',{exact:true}).selectOption('price-desc')
    await filters.getByRole('button',{name:'Ver resultados'}).click()
    await expect(page).toHaveURL(/price-desc/); await page.reload(); await expect(page).toHaveURL(/price-desc/)
    await noOverflow()
    await setup(page)
    await expect(page.locator('.mobile-account-button')).toBeHidden()
    await expect(page.locator('.provider-list label>span:last-child')).toHaveText(['WalletConnect','MetaMask','Coinbase Wallet'])
    await connect(page)
    await page.locator('.checkout-submit').focus(); await expect(page.locator('.checkout-submit')).toBeFocused()
    await noOverflow()
    await page.goto('/cart')
    await expect(page.locator('.cart-mobile-header')).toBeVisible()
    await expect(page.locator('.cart-fee-hint')).toHaveText('Taxa estimada')
    await page.locator('.cart-quantity input').fill('1')
    await page.getByRole('button',{name:'Atualizar quantidade'}).click()
    await expect(page.getByTestId('cart-total')).toHaveText('1.206 ETH')
    await noOverflow()
    await page.goto('/')
    await page.getByRole('link',{name:'Perfil',exact:true}).click()
    const account = page.getByRole('dialog',{name:'Minha conta',exact:true})
    await expect(account).toBeVisible(); await account.getByRole('link',{name:'Meu perfil',exact:true}).click()
    await expect(page).toHaveURL(/account\/profile/)
  })
}
