import { expect, test } from '@playwright/test'

test('detail quantity has a name, favorite has a usable target and selection has a shape', async ({ page }) => {
  await page.goto('/preparation')
  await expect(page.getByRole('link', { name: 'Abrir prova de integração' })).toBeVisible()
  expect(await page.evaluate(async () => (await fetch('/api/__scenario/reset', { method: 'POST' })).status)).toBe(200)
  await page.goto('/nfts/emerald-042')
  const quantity = page.getByRole('spinbutton', { name: 'Qtd.', exact: true })
  await expect(quantity).toBeVisible()
  await quantity.focus(); await expect(quantity).toBeFocused()
  expect(await quantity.evaluate(node => getComputedStyle(node).outlineWidth)).toBe('2px')
  const favorite = page.locator('.purchase-actions').getByRole('button', { name: 'Favoritar Emerald Ape #042' })
  const box = await favorite.boundingBox()
  expect(box!.width).toBeGreaterThanOrEqual(24)
  expect(box!.height).toBeGreaterThanOrEqual(24)
  await page.getByRole('button', { name: 'Edição 1/10', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edição 1/10', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.getByRole('button', { name: 'Edição 1/10', exact: true }).evaluate(node => getComputedStyle(node).boxShadow)).not.toBe('none')
  await page.getByRole('button', { name: 'Ampliar imagem' }).click()
  const dialog = page.getByRole('dialog', { name: 'Imagem do NFT' })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Tab')
  expect(await dialog.evaluate(node => node.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Ampliar imagem' })).toBeFocused()
})
