import { expect, test } from '@playwright/test'

test('forced colors preserve the selected edition and keyboard focus', async ({ page }) => {
  await page.emulateMedia({ forcedColors: 'active' })
  await page.goto('/nfts/emerald-042')
  const edition = page.getByRole('button', { name: 'Edição 1/10', exact: true })
  await edition.click()
  await edition.blur()
  await expect(edition).toHaveAttribute('aria-pressed', 'true')
  expect(await edition.evaluate(node => getComputedStyle(node).outlineStyle)).toBe('solid')
  const quantity = page.getByRole('spinbutton', { name: 'Qtd.', exact: true })
  await quantity.focus()
  await expect(quantity).toBeFocused()
  expect(await quantity.evaluate(node => getComputedStyle(node).outlineStyle)).toBe('solid')
})

test('authentication keeps its draft and keyboard CTA when the viewport shrinks without reload', async ({ page }) => {
  await page.goto('/signup')
  await page.getByLabel('Nome de usuário', { exact: true }).fill('zoom-draft')
  const dialog = page.getByRole('dialog', { name: 'Criar conta', exact: true })
  const wasDialog = await dialog.isVisible()
  const viewport = page.viewportSize()!
  await page.setViewportSize({ width: Math.max(320, Math.floor(viewport.width / 2)), height: Math.floor(viewport.height / 2) })
  await expect(page.getByLabel('Nome de usuário', { exact: true })).toHaveValue('zoom-draft')
  if (wasDialog) await expect.poll(() => dialog.evaluate(node => { const box = node.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight })).toBe(true)
  const submit = page.locator('.auth-form button[type=submit]')
  await submit.focus(); await expect(submit).toBeFocused()
  await expect.poll(() => submit.evaluate(node => { const box = node.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight })).toBe(true)
  await expect(page).toHaveURL(/\/signup/)
})

test('detail quantity has a name, favorite has a usable target and selection has a shape', async ({ page }) => {
  await page.goto('/preparation')
  await expect(page.getByRole('link', { name: 'Abrir prova de integração' })).toBeVisible()
  expect(await page.evaluate(async () => (await fetch('/api/__scenario/reset', { method: 'POST' })).status)).toBe(200)
  await page.goto('/nfts/emerald-042')
  const quantity = page.getByRole('spinbutton', { name: 'Qtd.', exact: true })
  await expect(quantity).toBeVisible()
  await quantity.focus(); await expect(quantity).toBeFocused()
  expect(await quantity.evaluate(node => getComputedStyle(node).outlineWidth)).toBe('2px')
  const favorite = page.locator('.detail-mobile-top,.purchase-actions').getByRole('button', { name: 'Favoritar Emerald Ape #042' }).filter({visible:true}).first()
  const box = await favorite.boundingBox()
  expect(box!.width).toBeGreaterThanOrEqual(24)
  expect(box!.height).toBeGreaterThanOrEqual(24)
  await page.getByRole('button', { name: 'Edição 1/10', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edição 1/10', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.getByRole('button', { name: 'Edição 1/10', exact: true }).evaluate(node => getComputedStyle(node).boxShadow)).not.toBe('none')
  await page.getByRole('button', { name: 'Ampliar imagem' }).click()
  const dialog = page.getByRole('dialog', { name: 'Imagem do NFT' })
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Tab')
  expect(await dialog.evaluate(node => node.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Ampliar imagem' })).toBeFocused()
})
