import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useSearch } from '@tanstack/react-router'
import { http } from '@/shared/api/http'
import { Field } from '@/shared/ui/Field'
import { EnsField } from '@/shared/ui/EnsField'
import { Button } from '@/shared/ui/button'
import { Skeleton } from '@/shared/ui/skeleton'
import { activeScope, apiFields, apiMessage, reportExpired, scopedConfig, useSession } from '@/features/auth/session'
import { AccountLayout } from '@/features/profile/AccountLayout'
import { profileOptions } from '@/features/profile/api'
import { networks } from '@/features/catalog/contracts'
import { safeReturn } from '@/features/auth/contracts'
import { providers, type WalletInput, type Wallet } from './contracts'
import { walletsKey, walletsOptions } from './api'

export function WalletsPage() {
  const session = useSession(), query = useQuery(walletsOptions(session.scope)), profile = useQuery(profileOptions(session.scope)), client = useQueryClient(), search = useSearch({ strict: false })
  const [secondary, setSecondary] = useState(false), navigate = useNavigate()
  const reuse = useMutation({ mutationFn: (enabled: boolean) => http.patch('/wallet-preferences', { reusePrimary: enabled }, scopedConfig(session.scope)), onSuccess: async () => { if (activeScope(client, session.scope)) await client.invalidateQueries({ queryKey: walletsKey(session.scope) }) }, onError: (error) => reportExpired(error, session.scope) })
  if (!query.data || !profile.data) return <AccountLayout title="Carteiras">{query.isError || profile.isError ? <div role="alert"><p>{apiMessage(query.error ?? profile.error)}</p><Button onClick={() => { void query.refetch(); void profile.refetch() }}>Tentar novamente</Button></div> : <Skeleton className="account-skeleton" />}</AccountLayout>
  return <AccountLayout title="Carteiras"><WalletForm kind="primary" initial={query.data.items.find((w) => w.kind === 'primary')} defaults={profile.data} /><section className="secondary-wallet"><h2>Carteira secundária</h2><label className="checkbox-label"><input type="checkbox" checked={query.data.reusePrimary} disabled={reuse.isPending} onChange={(e) => reuse.mutate(e.target.checked)} />Igual à carteira principal</label>{reuse.isError && <p role="alert">{apiMessage(reuse.error)}</p>}{query.data.reusePrimary ? <p>A carteira principal será usada também como secundária.</p> : secondary || query.data.items.some((w) => w.kind === 'secondary') ? <WalletForm kind="secondary" initial={query.data.items.find((w) => w.kind === 'secondary')} defaults={profile.data} /> : <><p>Você ainda não adicionou uma carteira secundária.</p><Button variant="outline" aria-label="Adicionar carteira secundária" onClick={() => setSecondary(true)}>Adicionar</Button></>}</section>{search.returnTo && search.returnTo !== '/' && <Button variant="outline" onClick={() => { void navigate({ href: safeReturn(search.returnTo) }) }}>Retomar fluxo</Button>}</AccountLayout>
}
function WalletForm({ kind, initial, defaults }: { kind: 'primary' | 'secondary'; initial?: Wallet; defaults: { displayName: string; username: string; email: string; nickname: string; ens: string } }) {
  const session = useSession(), client = useQueryClient()
  const mutation = useMutation({ mutationFn: (input: WalletInput) => initial ? http.patch(`/wallets/${initial.id}`, input, scopedConfig(session.scope)) : http.post('/wallets', input, scopedConfig(session.scope)), onSuccess: async () => { if (activeScope(client, session.scope)) await client.invalidateQueries({ queryKey: walletsKey(session.scope) }) }, onError: (error) => reportExpired(error, session.scope) })
  const fields = apiFields(mutation.error), values = { kind, displayName: defaults.displayName, username: defaults.username, email: defaults.email, ens: defaults.ens, nickname: kind === 'primary' ? defaults.nickname : 'Reserva', address: '', network: '', provider: '', referral: '', secondaryReference: '', ...initial }
  return <form className="wallet-form" aria-label={kind === 'primary' ? 'Carteira principal' : 'Carteira secundária'} onSubmit={(event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); mutation.mutate({ kind, displayName: String(data.displayName), nickname: String(data.nickname), network: String(data.network) as WalletInput['network'], address: String(data.address), provider: String(data.provider) as WalletInput['provider'], username: String(data.username), email: String(data.email), ens: String(data.ens), referral: String(data.referral), secondaryReference: String(data.secondaryReference) }) }}><h2>Carteira {kind === 'primary' ? 'principal' : 'secundária'}</h2>{kind === 'primary' && <p className="wallet-description">Estas carteiras ficam disponíveis no pagamento e para receber NFTs comprados.</p>}<div className="form-grid">{([['displayName', 'Nome de exibição'], ['nickname', 'Apelido da carteira'], ['network', 'Rede'], ['username', 'Nome do perfil'], ['address', 'Endereço da carteira'], ['secondaryReference', 'ENS ou carteira secundária (opcional)'], ['provider', 'Tipo de carteira'], ['referral', 'Código de indicação'], ['email', 'E-mail'], ['ens', 'Nome ENS']] as const).map(([name, label]) => name === 'ens' ? <EnsField key={name} value={values.ens} error={fields.ens} /> : <Field key={name} name={name} label={label} value={values[name]} requiredMarker={name !== 'secondaryReference'} hideLabel={name === 'secondaryReference'} placeholder={name === 'secondaryReference' ? label : name === 'address' ? 'Endereço 0x da carteira' : name === 'network' ? 'Selecione uma rede' : name === 'provider' ? 'Selecione uma carteira' : undefined} error={fields[name]} type={name === 'email' ? 'email' : 'text'} required={!['ens', 'referral', 'secondaryReference'].includes(name)} options={name === 'network' ? networks : name === 'provider' ? providers : undefined} />)}</div>{mutation.isError && <p role="alert">{apiMessage(mutation.error)}</p>}{mutation.isSuccess && <p role="status">Carteira salva.</p>}<Button disabled={mutation.isPending}>Salvar carteira</Button></form>
}
